version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: api
    container_name: mspr_iot_backend
    command: yarn start
    volumes:
      - ./api:/home/node/app
    environment:
      ENV: dev
      DB_HOST: db
      DB_NAME: mspr_iot
      DB_USER: root
      DB_PASSWORD: root
      API_PORT: ${API_PORT}
      API_HOST: localhost
      SECRETJWT: secret
    restart: unless-stopped
    expose:
      - ${API_PORT}
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: mspr_iot_database
    volumes:
      - ${PWD}/database:/var/lib/mysql
    command: --max_allowed_packet=32505856
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mspr_iot
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - backend

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    container_name: mspr_iot_webserver
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/dev/nginx:/etc/nginx/conf.d
      - ./infra/nginx/logs.log:/var/log/nginx/access.log
    ports:
      - 8081:${API_PORT}
    depends_on:
      - api
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
